In [ ]:
import pandas as pd
import torch
import numpy as np


In [2]:
data = pd.read_csv("college_student_placement_dataset.csv")

In [3]:
data.head()

College_ID   IQ  Prev_Sem_Result  CGPA  Academic_Performance  \
0    CLG0030  107             6.61  6.28                     8   
1    CLG0061   97             5.52  5.37                     8   
2    CLG0036  109             5.36  5.83                     9   
3    CLG0055  122             5.47  5.75                     6   
4    CLG0004   96             7.91  7.69                     7   

  Internship_Experience  Extra_Curricular_Score  Communication_Skills  \
0                    No                       8                     8   
1                    No                       7                     8   
2                    No                       3                     1   
3                   Yes                       1                     6   
4                    No                       8                    10   

   Projects_Completed Placement  
0                   4        No  
1                   0        No  
2                   1        No  
3                   1        No  
4                   2        No

In [4]:
data.drop(labels="College_ID",inplace=True,axis=1)

In [5]:
data.head()

IQ  Prev_Sem_Result  CGPA  Academic_Performance Internship_Experience  \
0  107             6.61  6.28                     8                    No   
1   97             5.52  5.37                     8                    No   
2  109             5.36  5.83                     9                    No   
3  122             5.47  5.75                     6                   Yes   
4   96             7.91  7.69                     7                    No   

   Extra_Curricular_Score  Communication_Skills  Projects_Completed Placement  
0                       8                     8                   4        No  
1                       7                     8                   0        No  
2                       3                     1                   1        No  
3                       1                     6                   1        No  
4                       8                    10                   2        No

In [6]:
data["Internship_Experience"].replace(to_replace=["No","Yes"],value=[0,1],
                                      inplace=True)

/tmp/ipykernel_7355/823045052.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Internship_Experience"].replace(to_replace=["No","Yes"],value=[0,1],


In [7]:
data.head()

IQ  Prev_Sem_Result  CGPA  Academic_Performance  Internship_Experience  \
0  107             6.61  6.28                     8                      0   
1   97             5.52  5.37                     8                      0   
2  109             5.36  5.83                     9                      0   
3  122             5.47  5.75                     6                      1   
4   96             7.91  7.69                     7                      0   

   Extra_Curricular_Score  Communication_Skills  Projects_Completed Placement  
0                       8                     8                   4        No  
1                       7                     8                   0        No  
2                       3                     1                   1        No  
3                       1                     6                   1        No  
4                       8                    10                   2        No

In [8]:
data["Placement"].replace(to_replace=["No","Yes"],value=[0,1],inplace=True)

/tmp/ipykernel_7355/1113174182.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Placement"].replace(to_replace=["No","Yes"],value=[0,1],inplace=True)


In [9]:
data.head()

IQ  Prev_Sem_Result  CGPA  Academic_Performance  Internship_Experience  \
0  107             6.61  6.28                     8                      0   
1   97             5.52  5.37                     8                      0   
2  109             5.36  5.83                     9                      0   
3  122             5.47  5.75                     6                      1   
4   96             7.91  7.69                     7                      0   

   Extra_Curricular_Score  Communication_Skills  Projects_Completed  Placement  
0                       8                     8                   4          0  
1                       7                     8                   0          0  
2                       3                     1                   1          0  
3                       1                     6                   1          0  
4                       8                    10                   2          0

In [11]:
X = torch.tensor(np.array(data.iloc[:,0:-1]))
y = np.array(data.iloc[:,-1])
y = y.reshape(y.shape[0],1)
y = torch.tensor(y)

In [12]:
print(X)

tensor([[107.0000,   6.6100,   6.2800,  ...,   8.0000,   8.0000,   4.0000],
        [ 97.0000,   5.5200,   5.3700,  ...,   7.0000,   8.0000,   0.0000],
        [109.0000,   5.3600,   5.8300,  ...,   3.0000,   1.0000,   1.0000],
        ...,
        [ 89.0000,   6.0800,   6.2500,  ...,   3.0000,   9.0000,   5.0000],
        [107.0000,   8.7700,   8.9200,  ...,   7.0000,   5.0000,   1.0000],
        [109.0000,   9.4100,   9.7700,  ...,   3.0000,   5.0000,   5.0000]],
       dtype=torch.float64)


In [14]:
torch.cuda.is_available()

False

In [18]:
class binary_classification_nn(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.first_hidden_layer = torch.nn.Linear(in_features=8,out_features=8)
        self.first_hidden_layer_function = torch.nn.ReLU()
        self.second_hidden_layer = torch.nn.Linear(in_features=8,out_features=8)
        self.second_hidden_layer_function = torch.nn.ReLU()
        self.output_layer = torch.nn.Linear(in_features=8,out_features=1)
        self.output_layer_function = torch.nn.Sigmoid()

    def forward(self,X):

        z2_vec = self.first_hidden_layer(X)
        h2_vec = self.first_hidden_layer_function(z2_vec)

        z3_vec = self.second_hidden_layer(h2_vec)
        h3_vec = self.second_hidden_layer_function(z3_vec)

        z4_vec = self.output_layer(h3_vec)
        y_hat = self.output_layer_function(z4_vec)

        return y_hat

In [19]:
model = binary_classification_nn()

In [21]:
for params in model.parameters():
    print(params)

Parameter containing:
tensor([[-0.2476, -0.3040,  0.2533, -0.3406, -0.1057,  0.2949,  0.3333, -0.2935],
        [-0.1821,  0.2795, -0.1427, -0.3438, -0.0342,  0.1847, -0.2296,  0.2112],
        [-0.1208,  0.1701,  0.1175,  0.1329,  0.0221,  0.2290, -0.2894,  0.3223],
        [ 0.3295,  0.1458,  0.2762, -0.2601, -0.1666, -0.0206, -0.1943,  0.3257],
        [-0.3079,  0.0152,  0.2368,  0.1383,  0.2559, -0.0624, -0.1819, -0.3199],
        [-0.0257,  0.1223,  0.0523,  0.0576,  0.1709,  0.0360,  0.0466, -0.3514],
        [ 0.1451,  0.2852, -0.1971,  0.0388, -0.1125, -0.0128, -0.2517, -0.1617],
        [-0.2265,  0.2802,  0.2465, -0.1377,  0.3186, -0.1862,  0.0334, -0.0285]],
       requires_grad=True)
Parameter containing:
tensor([-0.0116, -0.2929,  0.3144,  0.3274,  0.1499, -0.0692, -0.2254,  0.0099],
       requires_grad=True)
Parameter containing:
tensor([[ 0.2960, -0.1159,  0.3110,  0.2019, -0.0236,  0.0426, -0.2643,  0.1284],
        [ 0.2389,  0.3176,  0.1285, -0.1705,  0.2632,  0.281

In [ ]:
loss_function = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.RMSprop(params=model.parameters())