In [1]:
import pandas as pd
import torch
import numpy as np

In [2]:
data = pd.read_csv("college_student_placement_dataset.csv")

In [3]:
data.head()

College_ID   IQ  Prev_Sem_Result  CGPA  Academic_Performance  \
0    CLG0030  107             6.61  6.28                     8   
1    CLG0061   97             5.52  5.37                     8   
2    CLG0036  109             5.36  5.83                     9   
3    CLG0055  122             5.47  5.75                     6   
4    CLG0004   96             7.91  7.69                     7   

  Internship_Experience  Extra_Curricular_Score  Communication_Skills  \
0                    No                       8                     8   
1                    No                       7                     8   
2                    No                       3                     1   
3                   Yes                       1                     6   
4                    No                       8                    10   

   Projects_Completed Placement  
0                   4        No  
1                   0        No  
2                   1        No  
3                   1        No  
4                   2        No

In [4]:
data.drop(labels="College_ID",inplace=True,axis=1)

In [5]:
data.head()

IQ  Prev_Sem_Result  CGPA  Academic_Performance Internship_Experience  \
0  107             6.61  6.28                     8                    No   
1   97             5.52  5.37                     8                    No   
2  109             5.36  5.83                     9                    No   
3  122             5.47  5.75                     6                   Yes   
4   96             7.91  7.69                     7                    No   

   Extra_Curricular_Score  Communication_Skills  Projects_Completed Placement  
0                       8                     8                   4        No  
1                       7                     8                   0        No  
2                       3                     1                   1        No  
3                       1                     6                   1        No  
4                       8                    10                   2        No

In [6]:
data["Internship_Experience"].replace(to_replace=["No","Yes"],value=[0,1],
                                      inplace=True)

/tmp/ipykernel_15311/823045052.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Internship_Experience"].replace(to_replace=["No","Yes"],value=[0,1],
/tmp/ipykernel_15311/823045052.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Internship_Experience"].replace(to_replace=["No","Yes

In [7]:
data.head()

IQ  Prev_Sem_Result  CGPA  Academic_Performance  Internship_Experience  \
0  107             6.61  6.28                     8                      0   
1   97             5.52  5.37                     8                      0   
2  109             5.36  5.83                     9                      0   
3  122             5.47  5.75                     6                      1   
4   96             7.91  7.69                     7                      0   

   Extra_Curricular_Score  Communication_Skills  Projects_Completed Placement  
0                       8                     8                   4        No  
1                       7                     8                   0        No  
2                       3                     1                   1        No  
3                       1                     6                   1        No  
4                       8                    10                   2        No

In [8]:
data["Placement"].replace(to_replace=["No","Yes"],value=[0,1],inplace=True)

/tmp/ipykernel_15311/1113174182.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Placement"].replace(to_replace=["No","Yes"],value=[0,1],inplace=True)
/tmp/ipykernel_15311/1113174182.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Placement"].replace(to_replace=["No","Yes"],value=

In [9]:
data.head()

IQ  Prev_Sem_Result  CGPA  Academic_Performance  Internship_Experience  \
0  107             6.61  6.28                     8                      0   
1   97             5.52  5.37                     8                      0   
2  109             5.36  5.83                     9                      0   
3  122             5.47  5.75                     6                      1   
4   96             7.91  7.69                     7                      0   

   Extra_Curricular_Score  Communication_Skills  Projects_Completed  Placement  
0                       8                     8                   4          0  
1                       7                     8                   0          0  
2                       3                     1                   1          0  
3                       1                     6                   1          0  
4                       8                    10                   2          0

In [10]:
X = torch.tensor(np.array(data.iloc[:,0:-1]),dtype=torch.float32)
y = np.array(data.iloc[:,-1])
y = y.reshape(y.shape[0],1)
y = torch.tensor(y, dtype=torch.float32)

In [11]:
print(X)

tensor([[107.0000,   6.6100,   6.2800,  ...,   8.0000,   8.0000,   4.0000],
        [ 97.0000,   5.5200,   5.3700,  ...,   7.0000,   8.0000,   0.0000],
        [109.0000,   5.3600,   5.8300,  ...,   3.0000,   1.0000,   1.0000],
        ...,
        [ 89.0000,   6.0800,   6.2500,  ...,   3.0000,   9.0000,   5.0000],
        [107.0000,   8.7700,   8.9200,  ...,   7.0000,   5.0000,   1.0000],
        [109.0000,   9.4100,   9.7700,  ...,   3.0000,   5.0000,   5.0000]])


In [12]:
torch.cuda.is_available()

False

In [13]:
class binary_classification_nn(torch.nn.Module):

    def __init__(self):
        super().__init__()

        self.first_hidden_layer = torch.nn.Linear(in_features=8,out_features=8)
        self.first_hidden_layer_function = torch.nn.ReLU()
        self.second_hidden_layer = torch.nn.Linear(in_features=8,out_features=8)
        self.second_hidden_layer_function = torch.nn.ReLU()
        self.output_layer = torch.nn.Linear(in_features=8,out_features=1)

    def forward(self,X):

        z2_vec = self.first_hidden_layer(X)
        h2_vec = self.first_hidden_layer_function(z2_vec)

        z3_vec = self.second_hidden_layer(h2_vec)
        h3_vec = self.second_hidden_layer_function(z3_vec)

        y_hat = self.output_layer(h3_vec)

        return y_hat

In [20]:
model = binary_classification_nn()

In [21]:
for params in model.parameters():
    print(params)

Parameter containing:
tensor([[ 0.0142,  0.2571,  0.0652,  0.1746,  0.1575,  0.1755,  0.2568,  0.1440],
        [ 0.0900,  0.3114,  0.2410,  0.2306, -0.3079,  0.2268, -0.2638,  0.3401],
        [-0.3512,  0.1041,  0.0520,  0.0018, -0.0997,  0.2379, -0.0223,  0.0897],
        [-0.0850,  0.2441, -0.2242,  0.0844,  0.0974,  0.2750, -0.3068, -0.0037],
        [-0.0762, -0.1492,  0.0511,  0.1842, -0.2964, -0.0075,  0.0620,  0.2603],
        [ 0.2655, -0.2078,  0.2178, -0.3086, -0.2221, -0.0911, -0.0488, -0.0175],
        [-0.2177,  0.2142,  0.2249, -0.2588,  0.1062,  0.2230, -0.1312,  0.2508],
        [-0.0976,  0.2285,  0.2499,  0.2828, -0.2482,  0.2025,  0.2961,  0.0588]],
       requires_grad=True)
Parameter containing:
tensor([-0.2568, -0.0097, -0.0968, -0.0324,  0.0181, -0.3260,  0.3270,  0.1701],
       requires_grad=True)
Parameter containing:
tensor([[ 0.2953,  0.0316, -0.3228,  0.0264,  0.3118,  0.1962, -0.1307,  0.1259],
        [ 0.1114, -0.1442,  0.1204,  0.0325, -0.0713,  0.112

In [22]:
loss_function = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.RMSprop(params=model.parameters())
epoch = 0
tol = 10**(-6)

while True:

    initial_y_hat = model(X)
    initial_loss = loss_function(initial_y_hat,y)
    optimizer.zero_grad()
    initial_loss.backward()
    optimizer.step()
    final_y_hat = model(X)
    final_loss = loss_function(final_y_hat,y)

    epoch += 1
    if abs(final_loss.item() - initial_loss.item()) < tol:
        break

    print("Epoch #{}, BCE Loss Function Value = {}".format(epoch,initial_loss))

Epoch #1, BCE Loss Function Value = 3.3848445415496826
Epoch #2, BCE Loss Function Value = 0.48376619815826416
Epoch #3, BCE Loss Function Value = 0.49055400490760803
Epoch #4, BCE Loss Function Value = 0.773422360420227
Epoch #5, BCE Loss Function Value = 0.6676130294799805
Epoch #6, BCE Loss Function Value = 0.5079869031906128
Epoch #7, BCE Loss Function Value = 0.48259204626083374
Epoch #8, BCE Loss Function Value = 0.48122459650039673
Epoch #9, BCE Loss Function Value = 0.48009946942329407
Epoch #10, BCE Loss Function Value = 0.47888144850730896
Epoch #11, BCE Loss Function Value = 0.47731855511665344
Epoch #12, BCE Loss Function Value = 0.4752321243286133
Epoch #13, BCE Loss Function Value = 0.4732441306114197
Epoch #14, BCE Loss Function Value = 0.47159281373023987
Epoch #15, BCE Loss Function Value = 0.4703398048877716
Epoch #16, BCE Loss Function Value = 0.46917879581451416
Epoch #17, BCE Loss Function Value = 0.46798062324523926
Epoch #18, BCE Loss Function Value = 0.466672897